server:
  port: 8080

spring.sql.init.mode: always
  # в jdbc-url укажите, что данные нужно сохранять в файл

spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    password: password
    username: sa
    driverClassName: org.h2.Driver

